# 数据操作

In [26]:
import torch 

x = torch.arange(12)

print(x)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])


In [27]:
x.shape  # 可以通过张量的shape属性来访问张量（沿每个轴的长度）的形状 。

torch.Size([12])

In [28]:
x.reshape(3, 4)  # 改变一个张量的形状而不改变元素数量和元素值， reshape() 方法返回一个新的张量，而不会改变原始张量。如果你希望就地修改原始张量的形状，可以使用 view() 方法

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [29]:
x.reshape(-1, 2) # -1是让pytorch自己计算缺失的维度大小

tensor([[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9],
        [10, 11]])

In [30]:
x.reshape(3, -1)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [31]:
X = x.reshape(3 ,4)

X.shape

torch.Size([3, 4])

In [7]:
X.numel()  # 如果只想知道张量中元素的总数，即形状的所有元素乘积

12

In [8]:
torch.zeros((2, 3, 4))  # 创建一个形状为（2,3,4）的张量，其中所有元素都设置为0

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [9]:
torch.ones((2, 3, 4))  # 创建一个形状为（2,3,4）的张量，其中所有元素都设置为1

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [10]:
torch.randn(3, 4)  # 创建一个形状为（3,4）的张量。 其中的每个元素都从均值为0、标准差为1的标准高斯分布（正态分布）中随机采样

tensor([[ 1.2837,  0.4689, -1.1723,  1.0426],
        [-0.8496, -1.0421,  1.7743,  1.0962],
        [ 2.0016,  0.7456,  0.4208, -0.2838]])

# 运算符

In [11]:
x = torch.tensor([1.0, 2, 4, 8])
y = torch.tensor([2, 2, 2, 2])
x + y, x - y, x * y, x / y, x ** y  # **运算符是求幂运算

(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1.,  4., 16., 64.]))

In [12]:
torch.exp(x)  # e ^ x

tensor([2.7183e+00, 7.3891e+00, 5.4598e+01, 2.9810e+03])

In [13]:
X = torch.arange(12, dtype=torch.float32).reshape((3,4))  # 创建类型为float，形状为三行四列的张量X
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])  # 使用tensor（），通过列表创建张量Y
torch.cat((X, Y), dim=0), torch.cat((X, Y), dim=1)  # torch.cat()把多个张量连接在一起，dim=0时表示通过增加维度来连接，dim=1时表示通过增加长度来连接

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

In [14]:
X == Y  # 对于每个位置，如果X和Y在该位置相等，则新张量中相应项的值为1

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

In [15]:
X.sum()  # 对张量中的所有元素进行求和，会产生一个单元素张量

tensor(66.)

# 广播机制

1. 通过适当复制元素来扩展一个或两个数组，以便在转换之后，两个张量具有相同的形状；

2. 对生成的数组执行按元素操作。

In [16]:
a = torch.arange(3).reshape((3, 1))
b = torch.arange(2).reshape((1, 2))
a, b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [17]:
a + b  # 矩阵a将复制列， 矩阵b将复制行，然后再按元素相加

tensor([[0, 1],
        [1, 2],
        [2, 3]])

# 索引和切片

In [18]:
X, X[-1], X[1:3]  # [-1]选择最后一个元素，可以用[1:3]选择第二个和第三个元素(前闭后开),一个元素相当于一个行向量

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]),
 tensor([ 8.,  9., 10., 11.]),
 tensor([[ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]))

In [19]:
X[1, 2] = 9  # 改变矩阵中的值
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  9.,  7.],
        [ 8.,  9., 10., 11.]])

In [20]:
X[0:2, :] = 12  # 想为多个元素赋值相同的值，我们只需要索引所有元素，然后为它们赋值。 [0:2(表示1,2行)， :（表示所有列）]，
X

tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [ 8.,  9., 10., 11.]])

# 节省内存

In [21]:
before = id(Y)  # 这是因为Python首先计算Y + X，为结果分配新的内存，然后使Y指向内存中的这个新位置。
Y = Y + X
id(Y) == before

False

In [22]:
# 如果不想分配新的内存
Z = torch.zeros_like(Y)
print('id(Z):', id(Z))
Z[:] = X + Y
print('id(Z):', id(Z))

id(Z): 140641135199552
id(Z): 140641135199552


In [23]:
# 如果在后续计算中没有重复使用X，也可以用一下方法
before = id(X)
X += Y
id(X) == before

True

# 转换为其他Python对象

In [24]:
# numpy中的ndarray转换为torch中的tensor
A = X.numpy()
B = torch.tensor(A)
type(A), type(B)

(numpy.ndarray, torch.Tensor)

In [25]:
# 要将大小为1的张量转换为Python标量，我们可以调用item函数或Python的内置函数
a = torch.tensor([3.5])
a, a.item(), float(a), int(a)

(tensor([3.5000]), 3.5, 3.5, 3)